name: "Dune builder"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  builder:

    name: DuneBuilder

    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        coq_version:
          - '8.20.1'
        ocaml_version: ['default']

    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Coq
        uses: coq-community/docker-coq-action@v1
        with:
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}

      - name: Setup Dune
        run: |
          opam install dune
      
      - name: Add MMaps
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam install coq-mmaps
          
      - name: Build project via dune
        run: |
          eval $(opam config env)
          git clone https://github.com/JordanIschard/DeBrLevel
          cd DeBrLevel
          dune build
          dune install
          cd ..
          dune build

      - name: Generate documentation
        if: github.event_name == 'push'
        run: |
          eval $(opam config env)
          make coqdoc

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: doc/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
